language: haxe

haxe:
  - "3.2.0"
  - development

matrix:
  allow_failures:
    - haxe: development

addons:
  apt:
    packages:
      - python3
      - php5-cli
      - mono-devel
      - mono-mcs

install:
  - haxelib install hxcpp
  - haxelib install hxjava
  - haxelib install hxcs
  - haxelib list

script:
  - haxe build.hxml
  - haxe build.hxml -D ptr-no-out-of-bounds
